requires "Mouse";
requires "Test::Most";
requires "DBIx::Class";
requires "Mouse::Role";
requires "DBD::SQLite";
requires "experimental";
requires "perl", "5.38.3";
requires "Test::DBIx::Class";
requires "Syntax::Keyword::Try";
requires "DBIx::Class::Factory";
requires "DBIx::Class::Migration";
